version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.5
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  moodle:
    image: docker.io/moodlehq/moodle-php-apache:7.4
    ports:
      - '8080:80'
      - '8443:443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './public_html/moodle:/var/www/html'
      - './public_html/plugins:/var/www/plugins'
      - './private_html/moodledata:/var/www/moodledata'
      - './custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
