version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.5
    ports:
      - '3306:3306'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_USER=moodle
      - MARIADB_PASSWORD=moodle
      - MARIADB_DATABASE=moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  moodle:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '8080:80'
      - '443:443'
    volumes:
      - 'moodledata_data:/var/www/moodledata'
      - './public_html/html:/var/www/html'
      - './public_html/plugins:/var/www/plugins'
      - './custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  moodledata_data:
    driver: local
